"""Engine constants from docs/plan/02-adaptive-engine.md.

Every value here is tagged inferred in the plan and listed as a tunable in
docs/plan/12-open-questions.md. Change them there first.
"""
from datetime import date

GAMMA = 0.4
RHO = -0.2
LAMBDA = 0.0

BETA_PER_FACTOR = -0.35
BETA_CENTRE_FACTOR_COUNT = 2

MCQ_OPTION_COUNT = 4
MCQ_GUESS_FLOOR = 1.0 / MCQ_OPTION_COUNT
MCQ_SUCCESS_CREDIT = 1.0 - MCQ_GUESS_FLOOR

PROPAGATION_HARD_ONE_HOP = 0.3
PROPAGATION_HARD_TWO_HOP = 0.09
PROPAGATION_SUPPORTING_ONE_HOP = 0.1
PREREQUISITE_GAP_FAILURE = 1.0
PREREQUISITE_GAP_FORWARD_FAILURE = 0.3

MASTERY_THRESHOLD = 0.9
UNMASTERY_THRESHOLD = 0.75
MASTERY_MIN_UNAIDED_SUCCESSES = 3
MASTERY_MIN_DISTINCT_ARCHETYPES = 2
MASTERY_MIN_DISTINCT_DAYS = 3
MASTERY_MIN_DAY_SPAN = 7

FADING_ADVANCE_AFTER = 2
FADING_DROP_AFTER = 2

RETRIEVAL_ENTRY = 1

TARGET_LEARN = 0.80
STAGE_LOW = 0.50
STAGE_HIGH = 0.90
TARGET_DIAG_FR = 0.50
TARGET_DIAG_MCQ = TARGET_DIAG_FR * MCQ_SUCCESS_CREDIT + MCQ_GUESS_FLOOR

MAX_CONSECUTIVE_SAME_SKILL = 2
MIN_SKILLS_PER_10 = 4
MIN_UNITS_PER_10 = 2
MIN_TRANSLATION_SHARE = 0.20
MAX_FAMILY_PER_10 = 3

PROBE_QUEUE_MAX = 3
PROBE_TTL_DAYS = 7

DIAG_CAP = 30
DIAG_MIN = 10
GAP_DAYS_DIAGNOSTIC = 21

DECAYED_SUPPORT_CAP_RETRIEVABILITY = 0.5

BLOCK1_MAX_ITEMS = 5
BLOCK1_MAX_MINUTES = 5.0
BLOCK2_MAX_MINUTES = 25.0
BLOCK3_MIN_MINUTES = 10.0
BLOCK3_MAX_MINUTES = 15.0
FORECAST_DEFAULT_MINUTES = 3.0
FORECAST_MIN_ATTEMPTS = 5

REQUEUE_GAP_DAYS_MIN = 1
REQUEUE_GAP_DAYS_MAX = 2
HYPERCORRECTION_GAP_DAYS = 1
REPEAT_WINDOW_DAYS = 7

DESIRED_RETENTION_EARLY = 0.90
DESIRED_RETENTION_LATE = 0.95
DESIRED_RETENTION_SWITCH_DATE = date(2027, 3, 15)


def desired_retention(today):
   """P1 returns the early constant only. The dated switch arrives with FSRS scheduling in P2."""
   return DESIRED_RETENTION_EARLY
